worker_processes auto;
worker_cpu_affinity auto;

events {
    worker_connections 100000;
    multi_accept on;
    use epoll;
}

http {
    access_log off; # CRITICAL for 100k+ TPS, otherwise disk I/O blocks NGINX
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    upstream grpc_backend {
        least_conn; # Better distribution among the 8 ports
        
        server 192.168.0.130:50061;
        server 192.168.0.130:50062;
        server 192.168.0.130:50063;
        server 192.168.0.130:50064;
        server 192.168.0.130:50065;
        server 192.168.0.130:50066;
        server 192.168.0.130:50067;
        server 192.168.0.130:50068;

        # CRITICAL: Keep 1024 TCP connections permanently open to the i5 backend
        # Otherwise Nginx opens a new connection for EVERY SINGLE REQUEST
        keepalive 1024;
    }

    server {
        listen 443 ssl http2 reuseport;
        server_name localhost;

        # Fixed cert paths
        ssl_certificate     /etc/nginx/server.crt;
        ssl_certificate_key /etc/nginx/server.key;

        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 1d;

        # CRITICAL: Do not close HTTP/2 stream early
        http2_max_requests 10000000;

        location / {
            grpc_set_header authorization "";
            
            # Tell NGINX to reuse the keepalive TCP connections
            grpc_set_header Connection "";
            grpc_socket_keepalive on;
            
            # Disable proxy buffering to reduce latency
            grpc_buffering off;

            grpc_pass grpc://grpc_backend;
        }
    }
}
